export const commonPositionInCompany = [
  "Manager",
  "President",
  "Accountant",
  "Copywriter",
  "Bookkeeper",
  "Team Leader",
  "Coordinator",
  "Receptionist",
  "Administrative",
  "Project Manager",
  "Product Manager",
  "Business Analyst",
  "Graphic designer",
  "Marketing Manager",
  "Backend Developer",
  "Frontend Developer",
  "Executive assistant",
  "Human Resource Manager",
  "Chief Executive Officer",
  "Chief Operating Officer",
  "Chief Financial Officer",
];
